### ISSUE TITLE
Add peek functions to doubly::Linked

### ISSUE THREAD

**Issue by hawkw** [hawkw/alarm#10]
I think the peek functions for nodes will have to go on the `Linked` trait, but can just be written on top of `Linked::next`/`Linked::prev` where the `Linked` type can be borrowed as a `&T`. This will make the cursor implementation (#9) a little easier but probably isn't a strict blocker.

- [ ] `Linked::peek_next` 
- [ ] `Linked::peek_back`

Note that`List` already has peek functions, but they're called `List::front` and `List::back`. Should probably standardise on a naming scheme here.

**Comment by jdanford** [comment]
👋 I'd like to tackle this!

**Comment by hawkw** [comment]
@jdanford sounds good! I'm going to invite you to be a repo collaborator so I can assign the issue to you. If you have prior Rust experience, I don't think this will be too difficult, but please let me know if you need any pointers.
