### ISSUE TITLE
Implement Iter::Extend for doubly::List

### ISSUE THREAD

**Issue by hawkw** [hawkw/alarm#2]

**Comment by hawkw** [comment]
This is as easy as `push`ing everything in the input iterator into the list; can do this with a `for` loop. The only potential pain point I can see is ensuring the bounds necessary for `push` are met on the impl, but they can be just copied from here:
https://github.com/hawkw/alarm/blob/130023b601533e67d9717c618fb4db197f9b8fe6/intruder_alarm/src/doubly/mod.rs#L321-L325

**Comment by hawkw** [comment]
I believe @ynasser is interested in looking into this one?

**Comment by void-elf** [comment]
Yes, feel free to assign it to me!
