### ISSUE TITLE
Implement FromIterator for doubly::List

### ISSUE THREAD

**Issue by hawkw** [hawkw/alarm#3]

**Comment by hawkw** [comment]
Easiest way to do this is probably just to implement #2, and then have the `FromIterator` implementation make a new list and `extend()` it with the iterator.

**Comment by shubhamkumar13** [comment]
I am a complete beginner, how do I start?

**Comment by hawkw** [comment]
hi @shubhamkumar13, the absolute easiest way to implement this issue is to wait for the `iter::Extend` implementation (issue #2) and use that; but if you don't want to wait, we can do it with a `for` loop, which shouldn't be much harder.

If you're starting completely from scratch, the first thing you'll want to do is [install Rust](https://www.rustup.rs/). While you run the installer, you might want to take a look at [CONTRIBUTING.md](https://github.com/hawkw/alarm/blob/master/CONTRIBUTING.md) as well. :)

**Comment by shubhamkumar13** [comment]
Thanks, I'll look at #2

**Comment by hawkw** [comment]
@shubhamkumar13 #2 is already assigned, but I think we can implement this  issue pretty easily  without having to wait on it.

**Comment by shubhamkumar13** [comment]
ok

**Comment by shubhamkumar13** [comment]
what is a FromIterator?

**Comment by shubhamkumar13** [comment]
what is a FromIterator?

**Comment by leshow** [comment]
@shubhamkumar13 Are you still doing this one? If you're not, I have a solution ready. I didn't mean to take an already assigned issue, I was just trying to get the lib to compile and messing about.

**Comment by hawkw** [comment]
Just BTW @shubhamkumar13 sorry I wasn't able to provide more coaching on this issue this week --- been really busy with work.

**Comment by hawkw** [comment]
Closed by #20.
