### ISSUE TITLE
Update configuration for a recent version of rustfmt

### ISSUE THREAD

**Issue by amanjeev** [hawkw/alarm#34]
https://github.com/hawkw/alarm/issues/8#issuecomment-362090964 says that `rustfmt` configuration needs to be updated because the current config is of an out-of-date version of `rustfmt`.

**Comment by hawkw** [comment]
Thanks for reporting, @amanjeev! I'll try to make `rustfmt` stop complaining as soon as I have the chance.

**Comment by leshow** [comment]
I've been getting notifications that `rls.toml` is deprecated in vscode also, so we should probably remove that too

**Comment by hawkw** [comment]
@leshow yeah, I was previously using an Atom RLS plugin that required rls.toml, but have since switched to VS Code; that file can definitely be removed.
