### ISSUE TITLE
Refactor Singly Linked List - Rename to Stack

### ISSUE THREAD

**Issue by amanjeev** [hawkw/alarm#45]
Singly linked list implementation is mainly going to be used as a Stack so it is better if we refactor/rename to better reflect the function.

**Comment by hawkw** [comment]
Since we're in version 0.0.1, the Semver wild west, go ahead and make the change!

**Comment by amanjeev** [comment]
> version 0.0.1, the Semver wild west

🤣 

I think let's merge https://github.com/sos-os/alarm/pull/44 first, no?

**Comment by hawkw** [comment]
I'm also open to renaming the `doubly` and `singly` modules to `list` and `stack`, respectively --- at your discretion.

**Comment by amanjeev** [comment]
I like the idea of renaming `doubly` to just `list`. Perhaps another ticket though.
